### ISSUE TITLE
Crypto Support

### ISSUE THREAD

**Issue by Lowkey-C** [Bootstrap-Academy/Bootstrap-Academy#120]
### Bootstrap Academy username

Konsti

### Description

It would be cool if you can add crypto support so you can buy Morphcoins with Bitcoin/Ether/Monero or similar coins.

**Comment by TheMorpheus407** [comment]
I talked to my lawyer about this. She said, this is a horror scenario for us, because we'd need to do KYC - know your customer - aka we'd need to actually collect your ID cards. We definitely do not want that. So MorphCoin will not become a real crypto currency any time soon.

However - I think, what you rather meant was to implement a pay with crypto service. That I think shouldnt be a problem as long as we do not implement that ourselves. 

Did some research, but to be honest, I don't know the payment gateways too well. Maybe we can collect ideas on gateways here first?

**Comment by TheMorpheus407** [comment]
I will close this issue for now, since it's not a real priority for now. I will open a new one when we really focus on it to keep issues clean
