### ISSUE TITLE
404 when creating a quiz

### ISSUE THREAD

**Issue by RLeo** [Bootstrap-Academy/Bootstrap-Academy#93]
### Bootstrap Academy username

LeoR

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### What happened?

When I'm on a [lesson page](https://bootstrap.academy/courses/angular_5/watch?section=section&lecture=eTEEoAFoNNE&skillID=&subSkillID=) and click on "ADD TASK" I get a  [404 error page](https://bootstrap.academy/quizzes///create?course=angular_5&section=section&lecture=eTEEoAFoNNE&skillID=&subSkillID=&level=0)

![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/11270911/640c17af-3a6f-44e6-ba29-2131570ab2be)

**Comment by Lauritz-Tieste** [comment]
Is there any way or api endpoint to get the RootSkillID and the SubSkillID from a courseId?

**Comment by Lauritz-Tieste** [comment]
And from where can the Profile>Courses page get the information about `skillID` and `subSkillID` of the `my_courses`. Currently this information is missing there and therefore it is not passed on to the child components.

**Comment by TheMorpheus407** [comment]
Happened again. I was able to reproduce it with this URL: [https://bootstrap.academy/quizzes///create?course=machine_learning&section=section&lecture=pq8Ea5GqOv4&skillID=&subSkillID=&level=0](https://bootstrap.academy/quizzes///create?course=machine_learning&section=section&lecture=pq8Ea5GqOv4&skillID=&subSkillID=&level=0)
from here: [https://bootstrap.academy/courses/machine_learning/watch?section=section&lecture=pq8Ea5GqOv4&skillID=&subSkillID=](https://bootstrap.academy/courses/machine_learning/watch?section=section&lecture=pq8Ea5GqOv4&skillID=&subSkillID=)

I think its an error with redirects, since I got tripple slashes
